### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by Gisleburt** [ronanguilloux/php-gpio#1]
I seem to be having a problem controlling the GPIO pins using this script.

It seems to stem from the fact that the directories in

/sys/class/gpio

and their symlinked companion

/sys/devices/virtual/gpio

keep reverting back to being root:root.

Additionally, if I set the ownership to pi:pi and add read/write to group permissions the directory for the pin I'm accessing empties itself.

I feel like I'm missing something really obvious. At the moment my Apache server is running as pi:pi. What permissions and ownership do I need to set to make this work?

**Comment by ronanguilloux** [comment]
Hello Gisleburt,

Thanks a lot for your feedback: I augmented the README.md to explain how to configure your /etc/sudoers file in order to blink your leds using php-gpio with your Apache2 or Pi users. See the Api Usage & the Understanding I/O permissions sections.

Hope this will help you.

**Comment by Gisleburt** [comment]
Unless I'm mistaken that solution only really works for single scripts, not actually for the web server.

As an alternative I also created the following hack:

``` php
<?php
    while (true) {
        usleep(100000);
        exec('chmod 0777 /sys/class/gpio/gpio*/value');
    }
```

Then ran this script as route (you can kill it with Ctrl+C).

**Comment by ronanguilloux** [comment]
You're right: the solution I give works for single scripts. But that should work fine for web server solutions anyway. 

In fact a single blinker php script is needed to manage all your leds & make them blinking, one at a time: If you call the blinker.php script with appropriate php-cli [arguments](http://php.net/manual/en/features.commandline.options.php), by example a gpio-pin ID, and if you extend the blinker.php to manage such arguments, then just only one blinker.php script is needed to manage all the leds, and your webserver application doesn't need all php files to be specified in /etc/sudoers.

Also note that you could have written more pathes, one for each of your gpio device types by example.

``` bash
www-data ALL=NOPASSWD: /path/to/gpio1.php, /path/to/gpio2.php, /path/to/gpio3.php
```
