### ISSUE TITLE
Permissions for Exec

### ISSUE THREAD

**Issue by mbalderas** [ronanguilloux/php-gpio#3]
Hi,

I have been dealing with the Exec command, and the only way that worked for me was exec('sudo php blinker 17 20000');

It needed the php command, is this a permissions issue? It works fine localy, but through the network it doesn't.

**Comment by ronanguilloux** [comment]
Hello mbalderas,

Can you please elaborate on this: What does "throught the network" means : via ssh ? or when you implement php-gpio in a php-based website ? Have you any detailled examples (pieces of code to share with us), in order to to help you ?

**Comment by ronanguilloux** [comment]
Hello there,

I tkink the [php-gpio-web](https://github.com/ronanguilloux/php-gpio-web) project, that uses php-gpio lib, well explains how you can implement php-gpio in a website, the simple way.
