### ISSUE TITLE
getVersion() not working on B+

### ISSUE THREAD

**Issue by paucapo** [ronanguilloux/php-gpio#8]
This line is not working with B+ version (revision 0010).
https://github.com/ronanguilloux/php-gpio/blob/master/src/PhpGpio/Pi.php#L12

Looking in revision tables, maybe just with a return hexdec($matches[1]) gone work.

**Comment by paucapo** [comment]
And this is the pin list for B+ (for Gpio.php)

```
#gpio layout: B+
$this->pins = array(
                2, 3, 4, 5, 6, 7,
                8, 9, 10, 11, 12, 13,
                14, 15, 16, 17, 18, 19,
                20, 21, 22, 23, 24, 25,
                26, 27
);
$this->hackablePins = array();
```

**Comment by paucapo** [comment]
Another improvement:

In Gpio.php, method setup(), after export the pin number and before to set the direction:
while (!is_writable(GpioInterface::PATH_GPIO.$pinNo.'/direction'));

**Comment by ronanguilloux** [comment]
No Raspi b+ for now, so I just cannot test your propositions ; but acquiring one is part of my plans ;-)

A Pull Request should be useful.

Thanks
Ronan

**Comment by ronanguilloux** [comment]
A PR was merged to fix this: https://github.com/ronanguilloux/php-gpio/pull/10

Many thanks to @alexciarlillo !
